"""Unit tests for synomosia._llm_categorizer."""
from unittest.mock import patch, MagicMock

from synomosia._llm_categorizer import (
    categorize_article,
    categorize_batch,
    CONSPIRACY_CATEGORIES,
)


# ---------------------------------------------------------------------------
# CONSPIRACY_CATEGORIES list
# ---------------------------------------------------------------------------

def test_categories_list_not_empty():
    """CONSPIRACY_CATEGORIES should have at least 10 entries."""
    assert len(CONSPIRACY_CATEGORIES) >= 10


def test_categories_contains_expected_values():
    """Key conspiracy category strings are present."""
    assert "government-surveillance" in CONSPIRACY_CATEGORIES
    assert "secret-societies" in CONSPIRACY_CATEGORIES
    assert "mind-control" in CONSPIRACY_CATEGORIES
    assert "new-world-order" in CONSPIRACY_CATEGORIES


def test_categories_all_strings():
    """Every category is a non-empty string."""
    for cat in CONSPIRACY_CATEGORIES:
        assert isinstance(cat, str)
        assert cat.strip(), f"Empty category string found: {cat!r}"


def test_categories_are_lowercase_hyphenated():
    """Categories follow the lowercase-hyphenated naming convention."""
    for cat in CONSPIRACY_CATEGORIES:
        assert cat == cat.lower(), f"Category not lowercase: {cat!r}"
        assert " " not in cat, f"Category contains spaces: {cat!r}"


# ---------------------------------------------------------------------------
# categorize_article — LLM not available
# ---------------------------------------------------------------------------

def test_categorize_article_no_llm():
    """When LLM is not available, article is returned unchanged."""
    with patch("synomosia._llm_categorizer.LLMClient") as MockLLM:
        instance = MockLLM.get.return_value
        instance.is_available.return_value = False

        article = {"title": "Test Article", "summary": "Test summary text"}
        result = categorize_article(article)

        assert result == article
        instance.categorize.assert_not_called()
        instance.summarize.assert_not_called()
        instance.extract_topics.assert_not_called()


def test_categorize_article_no_llm_returns_same_object():
    """The exact same dict object is returned when LLM unavailable."""
    with patch("synomosia._llm_categorizer.LLMClient") as MockLLM:
        instance = MockLLM.get.return_value
        instance.is_available.return_value = False

        article = {"title": "NSA Spy Program", "summary": "Short text."}
        result = categorize_article(article)
        assert result is article


# ---------------------------------------------------------------------------
# categorize_article — LLM available
# ---------------------------------------------------------------------------

def test_categorize_article_with_llm_adds_category():
    """When LLM available, article gets a 'category' field set."""
    with patch("synomosia._llm_categorizer.LLMClient") as MockLLM:
        instance = MockLLM.get.return_value
        instance.is_available.return_value = True
        instance.categorize.return_value = "government-surveillance"
        instance.summarize.return_value = "A short LLM summary."
        instance.extract_topics.return_value = ["cia", "surveillance", "nsa"]

        article = {"title": "NSA Spying Program", "summary": "x" * 10}
        result = categorize_article(article)

        assert result["category"] == "government-surveillance"


def test_categorize_article_with_llm_adds_llm_topics():
    """When LLM available, article gets 'llm_topics' field set."""
    with patch("synomosia._llm_categorizer.LLMClient") as MockLLM:
        instance = MockLLM.get.return_value
        instance.is_available.return_value = True
        instance.categorize.return_value = "government-surveillance"
        instance.summarize.return_value = "A short LLM summary."
        instance.extract_topics.return_value = ["cia", "surveillance"]

        article = {"title": "NSA Spying Program", "summary": "x" * 10}
        result = categorize_article(article)

        assert "llm_topics" in result
        assert result["llm_topics"] == ["cia", "surveillance"]


def test_categorize_article_with_llm_short_summary_gets_replaced():
    """When summary is shorter than 50 chars, LLM summarize is called to replace it."""
    with patch("synomosia._llm_categorizer.LLMClient") as MockLLM:
        instance = MockLLM.get.return_value
        instance.is_available.return_value = True
        instance.categorize.return_value = "false-flag"
        instance.summarize.return_value = "A proper long summary generated by LLM."
        instance.extract_topics.return_value = []

        article = {"title": "Short Sum", "summary": "Too short."}
        result = categorize_article(article)

        instance.summarize.assert_called_once()
        assert result["summary"] == "A proper long summary generated by LLM."


def test_categorize_article_with_llm_long_summary_not_replaced():
    """When summary is >= 50 chars, LLM summarize is NOT called."""
    with patch("synomosia._llm_categorizer.LLMClient") as MockLLM:
        instance = MockLLM.get.return_value
        instance.is_available.return_value = True
        instance.categorize.return_value = "financial-manipulation"
        instance.extract_topics.return_value = []

        long_summary = "This summary is definitely longer than fifty characters total."
        article = {"title": "Long Summary Article", "summary": long_summary}
        result = categorize_article(article)

        instance.summarize.assert_not_called()
        assert result["summary"] == long_summary


def test_categorize_article_uses_content_when_no_summary():
    """If article has no 'summary', 'content' is used as fallback text."""
    with patch("synomosia._llm_categorizer.LLMClient") as MockLLM:
        instance = MockLLM.get.return_value
        instance.is_available.return_value = True
        instance.categorize.return_value = "extraterrestrial"
        instance.summarize.return_value = "Generated summary."
        instance.extract_topics.return_value = ["ufo", "aliens"]

        article = {"title": "UFO Crash", "content": "Eyewitnesses reported a craft."}
        result = categorize_article(article)

        instance.categorize.assert_called_once()
        assert result["category"] == "extraterrestrial"


# ---------------------------------------------------------------------------
# categorize_batch
# ---------------------------------------------------------------------------

def test_categorize_batch_no_llm():
    """categorize_batch returns the same number of articles even when LLM unavailable."""
    with patch("synomosia._llm_categorizer.LLMClient") as MockLLM:
        instance = MockLLM.get.return_value
        instance.is_available.return_value = False

        articles = [{"title": f"Article {i}"} for i in range(3)]
        result = categorize_batch(articles)

        assert len(result) == 3


def test_categorize_batch_preserves_order():
    """categorize_batch preserves article order in the returned list."""
    with patch("synomosia._llm_categorizer.LLMClient") as MockLLM:
        instance = MockLLM.get.return_value
        instance.is_available.return_value = False

        articles = [{"title": f"Article {i}", "id": i} for i in range(5)]
        result = categorize_batch(articles)

        for i, article in enumerate(result):
            assert article["id"] == i


def test_categorize_batch_empty_list():
    """categorize_batch handles an empty input list gracefully."""
    with patch("synomosia._llm_categorizer.LLMClient") as MockLLM:
        instance = MockLLM.get.return_value
        instance.is_available.return_value = False

        result = categorize_batch([])
        assert result == []


def test_categorize_batch_with_llm():
    """categorize_batch with LLM available enriches all articles."""
    with patch("synomosia._llm_categorizer.LLMClient") as MockLLM:
        instance = MockLLM.get.return_value
        instance.is_available.return_value = True
        instance.categorize.return_value = "secret-societies"
        instance.summarize.return_value = "LLM summary text here for the article."
        instance.extract_topics.return_value = ["freemasonry", "rituals"]

        articles = [{"title": f"Secret Society {i}", "summary": "Short."} for i in range(2)]
        result = categorize_batch(articles)

        assert len(result) == 2
        for r in result:
            assert r["category"] == "secret-societies"
            assert "llm_topics" in r
