#!/usr/bin/env python3
"""Generate rust/augur_core/src/entities.rs from CPython's own HTML tables.

Run from the repository root:

    python scripts/gen_html_entities.py

The Rust `unescape` must agree with `html.unescape` on every input, not on the
handful of entities that happen to appear in today's feeds. Hand-maintaining a
"common entities" subset would drift, and the drift would be invisible: a
mis-decoded article is still a valid article. Copying CPython's tables verbatim
makes the parity test in tests/test_rust_core.py exhaustive instead of
illustrative.
"""
from __future__ import annotations

import html
import html.entities
import io
from pathlib import Path

OUT = Path(__file__).resolve().parents[1] / "rust" / "augur_core" / "src" / "entities.rs"


def rs_str(s: str) -> str:
    """Render a Python str as a Rust string literal with no non-ASCII bytes."""
    buf = io.StringIO()
    buf.write('"')
    for ch in s:
        if ch == '"' or ch == "\\":
            buf.write("\\" + ch)
        elif " " <= ch <= "~":
            buf.write(ch)
        else:
            buf.write("\\u{%x}" % ord(ch))
    buf.write('"')
    return buf.getvalue()


def main() -> None:
    names = sorted(html.entities.html5.items())
    # Rust's &str Ord is byte order; every html5 key is ASCII, so Python's
    # sort matches it and binary search is valid.
    assert all(key.isascii() for key, _ in names), "non-ASCII entity name"

    invalid_refs = sorted(html._invalid_charrefs.items())
    invalid_cps = sorted(html._invalid_codepoints)
    longest = max(len(key) for key, _ in names)

    out: list[str] = []
    w = out.append
    w("//====== Augur/rust/augur_core/src/entities.rs ======//")
    w("//! HTML character-reference tables, generated by")
    w("//! `scripts/gen_html_entities.py`. Data only -- do not hand-edit.")
    w("//!")
    w("//! Verbatim copies of CPython's `html.entities.html5`,")
    w("//! `html._invalid_charrefs` and `html._invalid_codepoints`, so that")
    w("//! [`crate::text::unescape`] *is* `html.unescape` rather than an")
    w("//! approximation of it. A scraper that decodes `&eacute;` differently")
    w("//! from the Python it replaces corrupts stored article text silently.")
    w("")
    w("/// Longest key in [`NAMED_REFS`], in `char`s. Bounds the name scanner.")
    w(f"pub const MAX_ENTITY_NAME_CHARS: usize = {longest};")
    w("")
    w("/// `html.entities.html5`, sorted by key so lookup can binary-search.")
    w(f"pub static NAMED_REFS: [(&str, &str); {len(names)}] = [")
    for key, value in names:
        w(f"    ({rs_str(key)}, {rs_str(value)}),")
    w("];")
    w("")
    w("/// `html._invalid_charrefs`: numeric refs the standard remaps, sorted.")
    w(f"pub static INVALID_CHARREFS: [(u32, &str); {len(invalid_refs)}] = [")
    for code, value in invalid_refs:
        w(f"    ({code}, {rs_str(value)}),")
    w("];")
    w("")
    w("/// `html._invalid_codepoints`: numeric refs that decode to nothing.")
    w(f"pub static INVALID_CODEPOINTS: [u32; {len(invalid_cps)}] = [")
    for start in range(0, len(invalid_cps), 8):
        chunk = invalid_cps[start : start + 8]
        w("    " + " ".join(f"{code}," for code in chunk))
    w("];")
    w("")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(out), encoding="utf-8", newline="\n")
    print(f"wrote {OUT} ({len(out)} lines, {len(names)} named refs)")


if __name__ == "__main__":
    main()
